const PROJECTS = [
  {
    id: 'mahmoud-khalil',
    title: 'Mahmoud Khalil',
    year: '2025',
    medium: 'Digital Poster',
    pageUrl: 'project_pages/project.html?id=mahmoud-khalil',
    description: '<i><b>Art done in response to <a href="https://hellgatenyc.com/mahmoud-khalil-ice-columbia-trump-protest/" target="_blank">ICE\'s unjust detaining of Mahmoud Khalil</a>, and <a href="https://www.aclu.org/news/free-speech/a-letter-from-palestinian-activist-mahmoud-khalil" target="_blank">his released letter.</a></b></i><br><br>Mahmoud Khalil\'s words are a beacon of clarity and power: words that demand to be read, felt, and acted upon. Giving them visual form is one small act in answering his urgent call for justice, a call that requires all of us to rise.<br><br>Excerpt from the back of the print: "Free Mahmoud. Free Rumeysa. Liberation for all abducted, imprisoned, or forced into exile by the U.S. state and its occupation regimes—a machine built on stolen land, repression, and the bloody logic of capital. From Palestine to Guantánamo, the same system forges the same chains. Solidarity is our weapon. No one is free until all are free. Free Them All."',
    thumb: 'img/mahmoud-khalil-01.jpg',
    images: ['img/mahmoud-khalil-01.jpg', 'img/mahmoud-khalil-02.png'],
  },
  {
    id: 'queenslink',
    title: 'Support the QueensLink!',
    year: '2024',
    medium: 'Screenprinting on Fabric',
    pageUrl: 'project_pages/project.html?id=queenslink',
    description: 'Shirts made in support of the QueensLink project! <a href="https://store.seena.site/product/queenslink" target="_blank">Buy a shirt here ↗</a><br><br><i><b>What\'s the QueensLink?</b></i><br><br>"The QueensLink is a grassroots group fighting for reuse of a city-owned transit corridor that runs through central and south Queens that\'s been neglected for over 60 years. We want to put this treasure to work as part of New York\'s subway network, bringing inexpensive mass transit to transit deserts, and providing bicycle and walking paths, parks and other public spaces on 33 acres of land in the right-of-way not needed for rails and stations. QueensLink is a once in a lifetime opportunity to create a new backbone for sustainable transportation and recreation within New York City."<br><br>Read more: <a href="https://thequeenslink.org/" target="_blank">thequeenslink.org ↗</a>',
    thumb: 'img/queenslink-01.png',
    images: ['img/queenslink-01.png'],
  },
  {
    id: 'severed-city',
    title: 'severed city',
    year: '2023',
    medium: 'Relief Print & Screenprinting',
    pageUrl: 'project_pages/project.html?id=severed-city',
    description: 'This project began with a linocut relief print, which served as the foundation for a meticulous 12-color screenprint. It took me forever to finish, and some pieces are still in the works for future prints.',
    thumb: 'img/severed-city-01.jpg',
    images: ['img/severed-city-01.jpg', 'img/severed-city-02.jpg', 'img/severed-city-03.jpg'],
  },
  {
    id: 'we-are-the-land',
    title: 'we are the land',
    year: '2023',
    pageUrl: 'project_pages/project.html?id=we-are-the-land',
    medium: 'Collage & Screenprinting',
    description: '\'Land Back\' is a demand for the rights of American land to be restored back to its original caretakers, the people who are Indigenous to this land. It\'s not as simple as the title assumes, as in many cases it\'s not fully possible due to complicated historical development, but restoring Indigenous autonomy and power over their ancestral land is the goal.<br><br>Private property, a pillar of settler-colonialism, is directly opposed to the prosperity of our land and our people. Homelessness, excessive development, and neo-feudalism, all ills of modern day housing across the nation, are rooted in private property. The Land Back movement is strongly opposed to this, as many Indigenous civilizations only recognized private property in the form of houses and personal belongings, while land itself remained communal. The movement is less about a mass real estate transaction than it is about sovereignty, recognition of treaties, and, ultimately, the abolition of the United States\' conception of private property altogether. From many traditional Indigenous points of view, land ownership is an illusion, no more possible than ownership of a rainbow. Land "ownership" is simply a legal concept — one that keeps wealth and power in white families.<br><br>As the Red Nation demands in their Red Deal:<br><blockquote><i>"We demand Native Nations assume their rightful place as independent Nations guaranteeing the fundamental right to self-determination for their people, communities, land bases, and political and economic systems."</i></blockquote><br>This movement goes hand-in-hand with reparations, climate justice, and self-determination for all oppressed peoples, which is central to the idea that the people are the land and the land are the people.',
    layout: 'side-by-side',
    thumb: 'img/we-are-the-land-01.jpg',
    images: ['img/we-are-the-land-01.jpg'],
  },
  {
    id: 'apartheid-no-more',
    title: 'apartheid no more',
    year: '2023',
    medium: 'Digital Poster',
    pageUrl: 'project_pages/project.html?id=apartheid-no-more',
    description: 'My submission for <a href="https://againstapartheid.art" target="_blank">Artists Against Apartheid</a>. Inspired by the great Ismail Shammout. END THE SIEGE! Buy a print <a href="https://seena.bigcartel.com/product/freepalestine" target="_blank">here!</a> All proceeds go towards <a href="https://secure.everyaction.com/wroEGYAZS0-cUwhdirqSmQ2" target="_blank">PFC & MECA\'s Emergency Palestinian Aid Fund</a>.',
    thumb: 'img/apartheid-no-more-01.jpg',
    images: ['img/apartheid-no-more-01.jpg'],
  },
  {
    id: 'punitive-culture',
    title: 'punitive culture',
    year: '2022',
    medium: 'Collage, Silkscreen & Acrylic',
    pageUrl: 'project_pages/project.html?id=punitive-culture',
    description: 'Justice in America has always been seen through some sort of retribution — that justice can only be served when a person who commits a violation of law suffers in return. This distortion of justice often reciprocates the violence that the perpetrator committed.<br><br>With one-fourth of the world\'s incarcerated population, the American prison system boasts supreme control over 6.6 million people – one of the most violent and expansive systems in modern history. Many of these individuals won\'t see the light of day for the rest of their lives, and will not get to vote or participate in their communities ever again.<br><br>Those who eventually are released will not be able to get a job and will have trouble finding adequate housing. They might have even lost connection to their families through their incarceration, as often prisons are located in the suburbs away from urban areas. Family members thus have to travel long distances to see incarcerated loved ones, and those without access to a car or train may not be able to visit at all. Prisoners are isolated both mentally and spatially, and may end up completely desolate, which can lead to more violence and crime when they are released. In fact, up to 60 percent of released convicts are reconvicted within 2 years, furthering the cycle of violence through retribution. Regardless of wrongful or rightful conviction, or whether or not the judicial system worked to the best of its ability, these human beings will be affected for the rest of their lives.<br><br>My piece reflects on this culture that retributive justice has created — a cyclical and violent society that seeks vengeance through perpetual human suffering.',
    layout: 'side-by-side',
    thumb: 'img/punitive-culture-01.jpg',
    images: ['img/punitive-culture-01.jpg'],
  },
  {
    id: 'defend-the-forest',
    title: 'defend the forest',
    year: '2022',
    medium: 'Collage, Silkscreen & Acrylic',
    pageUrl: 'project_pages/project.html?id=defend-the-forest',
    description: 'Infuriated, saddened, and filled with rage. Across the US, continued investment in the militarization of the police comes at the expense of access to food, education, childcare, and healthcare, of affordable and stable housing, of parks and public spaces, of transit and the free movement of people, of economic stability for the many. Concentrating resources in the hands of police serves to defend the extreme accumulation of wealth and power by corporations and the very rich.&nbsp;<br><br>The state will continue to militarize while killing our loved ones and our land, and we will not stop fighting against their efforts. True justice will never be found under this system.&nbsp;<br><br>Extending my utmost solidarity with the Welaunee Forest Defenders of Atlanta, and my infinite love to Manny "Tortugita" Teran\'s family and friends.<br><br>We are the land.<br><br><i>Excerpts from <a href="https://crimethinc.com/" target="_blank"><u>Crime Thinc</u></a></i>',
    thumb: 'img/defend-the-forest-01.jpg',
    images: ['img/defend-the-forest-01.jpg'],
    layout: 'side-by-side',
  },
  {
    id: 'lie-cheat-and-steal',
    title: 'Lie, Cheat, & Steal:',
    subtitle: 'The CIA\'s Disastrous Scientific Legacy',
    year: '2022',
    medium: 'Collage, Silkscreen & Acrylic',
    pageUrl: 'project_pages/project.html?id=lie-cheat-and-steal',
    description: 'Infuriated, saddened, and filled with rage. Across the US, continued investment in the militarization of the police comes at the expense of access to food, education, childcare, and healthcare, of affordable and stable housing, of parks and public spaces, of transit and the free movement of people, of economic stability for the many. Concentrating resources in the hands of police serves to defend the extreme accumulation of wealth and power by corporations and the very rich.<br><br>The state will continue to militarize while killing our loved ones and our land, and we will not stop fighting against their efforts. True justice will never be found under this system.<br><br>Extending my utmost solidarity with the Welaunee Forest Defenders of Atlanta, and my infinite love to Manny "Tortugita" Teran\'s family and friends.<br><br>We are the land.<br><br><i>Excerpts from <a href="https://crimethinc.com/" target="_blank">CrimeThinc</a></i>',
    layout: 'side-by-side',
    thumb: 'img/liecheatsteal.gif',
    images: ['img/lie-cheat-and-steal-01.jpg'],
  },
  {
    id: 'community-power',
    title: 'community power!',
    year: '2021',
    medium: 'Wheatpaste & Spray Paint',
    pageUrl: 'project_pages/project.html?id=community-power',
    description: 'Community Power was a wheatpasting project that covered an abandoned storefront in Allston, which was scheduled for demolition in the next few years to make way for more luxury apartments. The project served as a continuation of a 2019 initiative where I pasted multiple buildings on a smaller scale. This time, my focus was on studying a specific space and neighborhood—this storefront in Allston. A decade before, it had been a co-op supermarket, but had deteriorated and was abandoned, plastered with graffiti, ads, and tattered posters. Across the street from this building stands a recently constructed luxury apartment development with rents exceeding $1,700 per person.<br><br>Allston, despite not being a wealthy neighborhood, is home to a vibrant and diverse community, mainly consisting of young students. It\'s one of the few neighborhoods in Boston that still retains a shared culture and sense of community, unlike the upscale and bourgeois Seaport or South End. Instead, it was a youth-centered community with a mix of Brazilian, Korean, and Middle Eastern influences. Unfortunately, this unique community is constantly under threat due to the ongoing expansion of housing giants like Harvard University, Boston University, Hamilton Company, and Alpha Management.<br><br>My goal for the project was not only to create visually appealing scenes, but also to inspire Allston residents to continue finding ways to empower their community and resist the control exerted by corporations over our city.<br><br><i>The project was located at <a href="https://goo.gl/maps/tsh5TVu1cqEV2zew7" target="_blank">449 Cambridge St, Allston</a>.</i>',
    layout: 'side-by-side',
    thumb: 'img/community-power-thumb01.png',
    images: ['img/community-power-01.jpg', 'img/community-power-02.jpg', 'img/community-power-03.jpg', 'img/community-power-04.jpg', 'img/community-power-05.jpg', 'img/community-power-06.jpg'],
  },
  {
    id: 'cooperation',
    title: 'cooperation:',
    subtitle: 'theory and practice for the commons',
    year: '2021',
    medium: 'Collage & Digital',
    pageUrl: 'project_pages/project.html?id=cooperation',
    description: '<i><b>Featured in:</b> Science for the People Magazine</i> (vol. 24, no. 3: <i>"Cooperation: Theory and Practice for the Commons"</i>)<br><br><a href="https://magazine.scienceforthepeople.org/vol24-3-cooperation/letter-from-the-editors-of-cooperation/" target="_blank">View issue ↗</a>',
    thumb: 'img/cooperation-01.jpg',
    images: ['img/cooperation-01.jpg', 'img/cooperation-02.jpg'],
  },
  {
    id: 'american-empire',
    title: 'The American Empire:',
    pageUrl: 'project_pages/project.html?id=american-empire',
    subtitle: 'International Purveyors of Violence',
    year: '2020',
    medium: 'Collage, Digital & Video',
    description: '"The U.S. is the greatest purveyor of violence in the world today." — Martin Luther King Jr.<br><br>America\'s modern empire is built on three interlocking systems of violence: imperialism abroad, the carceral state at home, and a culture that normalizes both. From the Cold War proxy conflicts to the War on Terror, from mass incarceration to policing, the machinery of American power sustains itself through the domination of people here and around the world.<br><br>This project is a visual and textual analysis of those systems — how they emerged, how they interlock, and how they are resisted.',
    layout: 'side-by-side',
    video: 'https://www.youtube.com/embed/pxAo8cqMMxo',
    thumb: 'img/american-empire_thumb.gif',
    images: ['img/american-empire_01.jpg', 'img/american-empire_02.jpg', 'img/american-empire_03.jpg'],
  },
  {
    id: 'squares',
    title: 'squares in america are just intersections..',
    year: '2020',
    medium: 'Zine & Screenprinting',
    pageUrl: 'project_pages/project.html?id=squares',
    description: 'Growing up in Boston, I\'ve always had a reoccurring thought as to why cities prioritize cars over people. Why are the cities we live in designed around cars? Why can\'t I reach certain areas without a car, and why aren\'t there better alternatives to individualized transportation? I figured to put these thoughts into a zine, and thus this project was made.',
    thumb: 'img/squares-01.jpg',
    images: ['img/squares-01.jpg', 'img/squares-02.jpg', 'img/squares-03.jpg', 'img/squares-04.jpg', 'img/squares-05.jpg', 'img/squares-06.jpg', 'img/squares-07.jpg', 'img/squares-08.jpg'],
  },
  {
    id: 'me',
    title: 'me',
    year: '2020',
    medium: 'Mixed Media Collage',
    pageUrl: 'project_pages/project.html?id=me',
    description: 'An artists\' self portrait is often a replication or projection of how they see themselves. Over the years, the way I\'ve represented myself in my art has fluctuated drastically. Whether that be a specific aesthetic or an emotion, the way I viewed myself differed as I grew. At one point, I decided to collect the various depictions of myself and throw them together in a collage. This is one of my few self portrait pieces, and what intrigues me about it is no matter what style I may draw myself, it\'s still me.',
    thumb: 'img/me_sleeping01.gif',
    images: ['img/me01.jpg'],
  },
  {
    id: 'portrait-study',
    title: 'portrait study',
    year: '2019',
    medium: 'Acrylic Painting',
    pageUrl: 'project_pages/project.html?id=portrait-study',
    description: '',
    thumb: 'img/portrait-study-01.jpg',
    images: ['img/portrait-study-01.jpg'],
  },
  {
    id: 'columbia-point',
    title: 'peoples history podcast: the point',
    year: '2019',
    medium: 'Intaglio',
    pageUrl: 'project_pages/project.html?id=columbia-point',
    description: 'I had the honor of creating limited prints for the People\'s History Podcast by Jacobin. The prints accompanied Season One of the podcast about public housing tenants in Boston, specifically the Columbia Point project. The podcast traces a social history of Boston from the urban rebellions of the 1960s, through busing in the 70s, into the Clinton era.<br><br><a href="https://peopleshistorypod.net" target="_blank">View Podcast ↗</a><br><a href="https://www.patreon.com/peopleshistorypod" target="_blank">Become a patron to receive a print ↗</a>',
    thumb: 'img/columbia-point-01.jpg',
    images: ['img/columbia-point-01.jpg', 'img/columbia-point-02.jpg'],
  },
  {
    id: 'who-protects-us-from-you',
    title: 'who protects us from you?',
    year: '2019',
    medium: 'Intaglio & Silkscreen',
    pageUrl: 'project_pages/project.html?id=who-protects-us-from-you',
    description: 'A series of both etchings and screen prints, focused on the reality of the American carceral system and the violence perpetrated by it. Inspired by the great Emory Douglas\' work.',
    thumb: 'img/who-protects-us-from-you-01.jpg',
    images: ['img/who-protects-us-from-you-01.jpg', 'img/who-protects-us-from-you-02.jpg', 'img/who-protects-us-from-you-03.jpg', 'img/who-protects-us-from-you-04.jpg', 'img/who-protects-us-from-you-05.jpg', 'img/who-protects-us-from-you-06.jpg'],
  },
  {
    id: 'eyes-on-you',
    title: 'eyes on you',
    year: '2019',
    medium: 'Intaglio Etching',
    pageUrl: 'project_pages/project.html?id=eyes-on-you',
    description: '',
    thumb: 'img/eyes-on-you-01.png',
    images: ['img/eyes-on-you-01.jpg', 'img/eyes-on-you-02.jpg'],
  },
  {
    id: 'two-nudes',
    title: 'two nudes',
    year: '2018',
    medium: 'Oil Painting',
    pageUrl: 'project_pages/project.html?id=two-nudes',
    description: 'Master copy of Oskar Kokoschka\'s <a href="https://www.mfa.org/collections/object/two-nudes-lovers-34173" target="_blank">Two Nudes (Lovers)</a>.',
    thumb: 'img/twonudes01.jpg',
    images: ['img/twonudes01.jpg'],
  },
  {
    id: 'postersflyers',
    title: 'posters/flyers',
    year: '2018–forever',
    medium: 'Poster & Flyer Design',
    pageUrl: 'project_pages/project.html?id=postersflyers',
    description: 'Various posters and flyers i\'ve made for various people, organizations, and events.',
    layout: 'grid',
    thumb: 'img/postersflyers thumb.png',
    images: ['img/postersflyers-01.jpg', 'img/postersflyers-02.png', 'img/postersflyers-03.jpg', 'img/postersflyers-04.png', 'img/postersflyers-05.jpg', 'img/postersflyers-06.jpg', 'img/postersflyers-07.jpg', 'img/postersflyers-08.jpg', 'img/postersflyers-09.png', 'img/postersflyers-10.jpg', 'img/postersflyers-11.jpg', 'img/postersflyers-12.jpg', 'img/postersflyers-13.jpg', 'img/postersflyers-14.jpg', 'img/postersflyers-15.jpg', 'img/postersflyers-16.jpg', 'img/postersflyers-17.jpg', 'img/postersflyers-18.jpg', 'img/postersflyers-19.jpg', 'img/postersflyers-20.jpg', 'img/postersflyers-21.jpg'],
  },
];
